import {useState} from 'react';
import DuckPreview from './three/DuckPreview';
import {DUCKS} from './palette';
import {unlockAudio,squeak} from './squeak';
export default function NameEntry({onJoin,count,error,initialRoom}:{onJoin:(name:string,index:number,room:string)=>Promise<void>;count:number;error?:string;initialRoom:string}){
 const [room,setRoom]=useState(initialRoom);
 const [index,setIndex]=useState(()=>Number(localStorage.getItem('duckoff_duck')??0)%8);const [name,setName]=useState(()=>localStorage.getItem('duckoff_name')??'');const [busy,setBusy]=useState(false);
 const change=(d:number)=>{unlockAudio();setIndex((index+d+8)%8);squeak((index+d+8)%8,.18)};
 return <main className="entry-screen"><header className="entry-top"><span className="brand-mini">DUCK OFF!</span><span className="live-pill"><i/> YOUR ROOM. YOUR FLOCK.</span></header><div className="entry-content"><div className="entry-heading"><div className="eyebrow">SMALL DUCKS. BIG ENERGY.</div><h1 className="logo">DUCK OFF<span>!</span></h1><p>The 5-second party race.</p><div className="tagline">Join the same room as your friends — tap your duck the fastest.</div></div><section className="entry-card"><div className="card-heading"><span>CHOOSE YOUR CHAOS</span><span className="character-number">0{index+1} <b>/ 08</b></span></div><div className="picker"><div className="preview-water"><span className="preview-spark s1">✦</span><span className="preview-spark s2">✧</span><DuckPreview index={index}/><span className="water-line w1"/><span className="water-line w2"/><span className="water-line w3"/></div><button className="arrow prev" aria-label="Previous duck" onClick={()=>change(-1)}>‹</button><button className="arrow next" aria-label="Next duck" onClick={()=>change(1)}>›</button><span className="toy-sticker">100%<br/>QUACK</span></div><div className="character-info"><h2>{DUCKS[index][0]}</h2><span>{DUCKS[index][1]}</span></div><div className="picker-dots">{DUCKS.map((d,i)=><button key={d[0]} aria-label={d[0]} aria-pressed={i===index} onClick={()=>setIndex(i)} className={i===index?'selected':''}/>)}</div><form onSubmit={async e=>{e.preventDefault();unlockAudio();squeak(index);setBusy(true);try{await onJoin(name,index,room)}finally{setBusy(false)}}}><label htmlFor="duck-name">NAME YOUR DUCK <span>make it quack.</span></label><div className="name-input"><input id="duck-name" placeholder="name your duck" maxLength={14} value={name} onChange={e=>setName(e.target.value)} autoComplete="off"/><span>{name.length}/14</span></div><label className="room-label" htmlFor="room-code">ROOM CODE <span>same code, same river.</span></label><div className="name-input"><input id="room-code" value={room} maxLength={16} pattern="[A-Za-z0-9-]{1,16}" required onChange={e=>setRoom(e.target.value.toUpperCase())} autoComplete="off" autoCapitalize="characters" spellCheck={false}/></div><button className="new-room" type="button" onClick={()=>setRoom(crypto.randomUUID().slice(0,8).toUpperCase())}>Create a new room ↗</button><button className="primary" disabled={busy}>{busy?'HOPPING IN…':'HOP IN THE TUB'} <span>↗</span></button>{error&&<p className="form-error" role="alert">{error}</p>}</form><div className="card-footer"><span className="little-light"/>{count?`${count} ${count===1?'duck':'ducks'} in the tub`:'The river’s ready. Make a splash.'}</div></section><p className="entry-note"><span>↳</span> Pick a duck. Tap like mad. Blame the water.</p></div><footer className="entry-footer"><span>NO LOGINS. SHARE A ROOM. JUST QUACKS.</span><span>sound on for maximum squeak <b>♫</b></span></footer><div className="edge-wave"/></main>
}
