import {useEffect,useRef,useState,useCallback} from 'react';
import RaceScene from './three/RaceScene';
import DuckPreview from './three/DuckPreview';
import {ordinal,DUCK_COLORS} from './palette';
import {squeak,unlockAudio,setMuted} from './squeak';
import type {Player,Race,RacePlayer,RaceResult} from './module_bindings/types';
type Props={race:Race;players:readonly RacePlayer[];legends:readonly Player[];results:readonly RaceResult[];identity:string;onTap:()=>Promise<void>;onStart:()=>Promise<void>;onEdit:()=>void};
export default function RaceScreen({race,players,legends,results,identity,onTap,onStart,onEdit}:Props){
 const [muted,updateMuted]=useState(false),[error,setError]=useState(''),[starting,setStarting]=useState(false),[copied,setCopied]=useState(false),[showLink,setShowLink]=useState(false),[showRanks,setShowRanks]=useState(false);
 const lastTap=useRef(0),tapPending=useRef(0);
 const mine=players.find(p=>p.identity.toHexString()===identity),racing=race.status==='racing',spectator=!mine?.active,finished=race.status==='finished';
 const secs=Math.ceil(race.phaseTicksLeft/10),online=legends.filter(p=>p.online),active=players.filter(p=>p.active),standings=[...active].sort((a,b)=>a.rank-b.rank),orderedResults=[...results].sort((a,b)=>a.place-b.place),myResult=results.find(p=>p.identity.toHexString()===identity);
 const leaders=[...legends].filter(p=>p.racesWon>0).sort((a,b)=>b.racesWon-a.racesWon||(a.identity.toHexString()<b.identity.toHexString()?-1:1)).slice(0,3);
 const url=new URL(location.href);url.searchParams.set('room',race.id);
 const shareRoom=async()=>{try{await navigator.clipboard.writeText(url.toString());setCopied(true)}catch{setShowLink(true)}};
 const start=async()=>{unlockAudio();setStarting(true);setError('');try{await onStart()}catch{setError('Couldn’t start just yet. Please try again.')}finally{setStarting(false)}};
 const tap=useCallback(()=>{
  if(!racing||spectator||mine?.place)return;const now=performance.now();if(now-lastTap.current<40||tapPending.current>=4)return;
  lastTap.current=now;tapPending.current++;unlockAudio();squeak(mine?.duckIndex??0,.13);
  void onTap().catch(()=>setError('Connection hiccup. Keep your duck here and try another tap.')).finally(()=>tapPending.current--);
 },[racing,spectator,mine,onTap]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.code==='Space'||e.code==='Enter')&&!e.repeat&&!(e.target as HTMLElement).closest('button,input,textarea,summary')){e.preventDefault();tap()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[tap]);
 useEffect(()=>{setShowRanks(false);setError('')},[race.status]);
 const startButton=<button className="primary start-button" disabled={starting} onClick={start}>{starting?'Gathering the ducks…':finished?'Play again':'Start race'} <span aria-hidden="true">↗</span></button>;
 return <main className={`race-screen phase-${race.status}`} data-phase={race.status}>
  <div className="river-fallback" aria-hidden="true"><div className="fallback-racers">{active.map((p,i)=><span key={p.identity.toHexString()} style={{left:`${8+i/Math.max(active.length,1)*80}%`,bottom:`${10+p.pos/2400*65}%`}}>🦆<small>{p.name}</small></span>)}</div></div>
  <div className="scene-layer" onPointerDown={e=>{if(e.isPrimary)tap()}}><RaceScene race={race} players={players} identity={identity}/></div>
  <header className="race-header"><div className="race-brand"><span className="brand-mini">duck off<span>!</span></span><span className="race-number">Race {race.raceNumber}</span></div><div className="header-actions"><button className="icon-button" aria-label="Change your duck" onClick={onEdit}>✎</button><button className="icon-button" aria-label={muted?'Unmute squeaks':'Mute squeaks'} onClick={()=>{unlockAudio();updateMuted(!muted);setMuted(!muted)}}>{muted?'♪̸':'♫'}</button></div></header>
  {!finished&&<div className="room-strip"><span>ROOM <b>{race.id}</b></span><button onClick={shareRoom}>{copied?'Copied ✓':'Invite friends ↗'}</button></div>}
  {showLink&&<div className="share-fallback"><label htmlFor="share-link">Copy this room link</label><input id="share-link" readOnly value={url.toString()} onFocus={e=>e.target.select()}/><button className="text-button" onClick={()=>setShowLink(false)}>Done</button></div>}
  {race.status==='lobby'&&<section className="lobby-panel surface"><div className="eyebrow">THE FLOCK IS GATHERING</div><h1>Everyone here?</h1><p>Share your room. Start when you’re ready.</p><div className="roster" aria-label="Players in the room">{online.map(p=><span key={p.identity.toHexString()}><i style={{background:DUCK_COLORS[p.duckIndex]}} aria-hidden="true">♥</i>{p.name}{p.identity.toHexString()===identity&&<small>you</small>}</span>)}</div>{startButton}<span className="panel-note">{online.length} {online.length===1?'duck':'ducks'} ready · anyone can start</span></section>}
  {race.status==='countdown'&&<section className="countdown-overlay" aria-live="assertive"><p>{spectator?'You’ll join the next race':'Little wings at the ready…'}</p><strong key={secs}>{secs}</strong><span>Tap the big button when it says GO!</span></section>}
  {racing&&<><section className="race-status"><span className="status-pill">{spectator?'CHEERING SECTION':mine?.place?`${ordinal(mine.place)} · FINISHED`:`${ordinal(mine?.rank||1)} of ${active.length}`}</span><button className="status-pill" onClick={()=>setShowRanks(!showRanks)} aria-expanded={showRanks}>{showRanks?'Close standings':'Standings'} {showRanks?'×':'↗'}</button><span className="status-pill timer">{secs}s</span></section>
   {showRanks&&<section className="live-standings surface" aria-label="Live standings"><h2>Little league leaders</h2><ol>{standings.map(p=><li key={p.identity.toHexString()} className={p.identity.toHexString()===identity?'is-you':''}><b>{p.rank}</b><span>{p.name}{p.identity.toHexString()===identity?' (you)':''}</span><small>{p.place?'Finished':`${Math.floor(p.pos/24)}%`}</small></li>)}</ol></section>}
   {race.phaseTicksLeft>390&&!showRanks&&<div className="go-flash" aria-live="polite">GO!</div>}
   <section className="race-controls">{spectator?<div className="waiting-message surface"><h2>Your turn is coming.</h2><p>Enjoy the splashes. You’re in the next race.</p></div>:mine?.place?<div className="waiting-message surface"><h2>A {ordinal(mine.place)} place splash!</h2><p>Let’s cheer the others home.</p></div>:<><div className="progress-info"><span>{Math.floor((mine?.pos??0)/24)}% of the way</span><span>{mine?.boostTicksLeft?'A little extra whoosh!':`${mine?.boostMeter??0}/20 to a boost`}</span></div><div className="boost-track" role="progressbar" aria-label="Boost meter" aria-valuemin={0} aria-valuemax={20} aria-valuenow={mine?.boostTicksLeft?20:mine?.boostMeter??0}><div style={{width:`${mine?.boostTicksLeft?100:(mine?.boostMeter??0)*5}%`}}/></div><button className={`tap-button ${mine?.boostTicksLeft?'boosting':''}`} onPointerDown={e=>{e.preventDefault();if(e.isPrimary)tap()}} onClick={e=>{if(e.detail===0)tap()}}>TAP, LITTLE DUCK! <span aria-hidden="true">♡</span></button><p className="control-note">Tiny taps. Big splash. <span>Space / Enter works too.</span></p></>}</section>
  </>}
  {finished&&<div className="results-scroll"><section className="results-card surface" aria-label="Race results"><div className="eyebrow">A VERY GOOD LITTLE RACE</div><h1>{orderedResults[0]?.name??race.winnerName} wins!</h1><div className="winner-portrait"><DuckPreview index={orderedResults[0]?.duckIndex??race.winnerDuckIndex}/><span className="winner-medal">1</span></div><p className="result-message">{myResult?`You splashed into ${ordinal(myResult.place)}. ${myResult.place===1?'Look at you go!':'Your duck is proud of you.'}`:'Your little duck is up next.'}</p>
   <ol className="results-list" aria-label="Final rankings">{orderedResults.map(p=><li key={p.id} data-place={p.place} className={p.identity.toHexString()===identity?'is-you':''}><b className="result-place">{p.place<=3?['①','②','③'][p.place-1]:p.place}</b><span className="result-name">{p.name}{p.identity.toHexString()===identity&&<small>you</small>}<em>{p.pos>=2400?'Crossed the line':`${Math.floor(p.pos/24)}% at the buzzer`}</em></span><span className="result-taps">{p.taps}<small>taps</small></span></li>)}</ol>
   <p className="ranking-note">Finishers first. At the buzzer, remaining ducks are ranked by distance. Exact ties use a fixed order.</p><section className="legends" aria-label="Flock legends"><h2>Flock legends</h2><p>Lifetime wins · ducks in this room</p>{leaders.length?<ol>{leaders.map(p=><li key={p.identity.toHexString()}><span>{p.name}</span><b>{p.racesWon} {p.racesWon===1?'win':'wins'}</b></li>)}</ol>:<p>The first little legend is on the way.</p>}</section><div className="results-actions">{startButton}<button className="text-button" onClick={onEdit}>Pick another duck or room</button><span className="panel-note">No automatic rematch. Take your time. ♡</span></div>
  </section></div>}
  {error&&<div className="connection-warning" role="alert"><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
 </main>;
}
