// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.u64().primaryKey(),
  room: __t.string(),
  source: __t.identity(),
  target: __t.identity(),
  kind: __t.string(),
  sourcePos: __t.f64().name('source_pos'),
  targetPos: __t.f64().name('target_pos'),
  flightTicks: __t.u32().name('flight_ticks'),
  lifeTicks: __t.u32().name('life_ticks'),
  blocked: __t.bool(),
});
