// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  identity: __t.identity().primaryKey(),
  room: __t.string(),
  name: __t.string(),
  duckIndex: __t.u8().name('duck_index'),
  online: __t.bool(),
  racesWon: __t.u32().name('races_won'),
  racesPlayed: __t.u32().name('races_played'),
  lastSeen: __t.timestamp().name('last_seen'),
});
