// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  room: __t.string(),
  name: __t.string(),
  duckIndex: __t.u8().name("duck_index"),
  active: __t.bool(),
  lane: __t.u8(),
  pos: __t.f64(),
  vel: __t.f64(),
  taps: __t.u32(),
  boostMeter: __t.u32().name("boost_meter"),
  boostTicksLeft: __t.u32().name("boost_ticks_left"),
  place: __t.u32(),
  rank: __t.u32(),
  lastTapAt: __t.u64().name("last_tap_at"),
  drowned: __t.bool(),
  bonks: __t.u32(),
  seconds: __t.f64(),
});
