// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.row({
  id: __t.string().primaryKey(),
  status: __t.string(),
  phaseTicksLeft: __t.u32().name('phase_ticks_left'),
  finishCounter: __t.u32().name('finish_counter'),
  raceNumber: __t.u32().name('race_number'),
  winnerName: __t.string().name('winner_name'),
  winnerDuckIndex: __t.u8().name('winner_duck_index'),
  idleTicks: __t.u32().name('idle_ticks'),
  forfeited: __t.bool(),
  forfeitReason: __t.string().name('forfeit_reason'),
  solo: __t.bool(),
  hostIdentity: __t.string().name('host_identity'),
  mode: __t.string(),
  elapsedTicks: __t.u32().name('elapsed_ticks'),
});
