// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  room: __t.string(),
  held: __t.string(),
  nextPickup: __t.u32().name("next_pickup"),
  slowTicks: __t.u32().name("slow_ticks"),
  shieldTicks: __t.u32().name("shield_ticks"),
  turboTicks: __t.u32().name("turbo_ticks"),
});
