// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export const ItemEffect = __t.object('ItemEffect', {
  id: __t.u64(),
  room: __t.string(),
  source: __t.identity(),
  target: __t.identity(),
  kind: __t.string(),
  sourcePos: __t.f64(),
  targetPos: __t.f64(),
  flightTicks: __t.u32(),
  lifeTicks: __t.u32(),
  blocked: __t.bool(),
});
export type ItemEffect = __Infer<typeof ItemEffect>;

export const Player = __t.object('Player', {
  identity: __t.identity(),
  room: __t.string(),
  name: __t.string(),
  duckIndex: __t.u8(),
  online: __t.bool(),
  racesWon: __t.u32(),
  racesPlayed: __t.u32(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Presence = __t.object('Presence', {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
});
export type Presence = __Infer<typeof Presence>;

export const Race = __t.object('Race', {
  id: __t.string(),
  status: __t.string(),
  phaseTicksLeft: __t.u32(),
  finishCounter: __t.u32(),
  raceNumber: __t.u32(),
  winnerName: __t.string(),
  winnerDuckIndex: __t.u8(),
  idleTicks: __t.u32(),
  forfeited: __t.bool(),
  forfeitReason: __t.string(),
  solo: __t.bool(),
  hostIdentity: __t.string(),
  mode: __t.string(),
  elapsedTicks: __t.u32(),
});
export type Race = __Infer<typeof Race>;

export const RaceFeature = __t.object('RaceFeature', {
  id: __t.u64(),
  room: __t.string(),
  kind: __t.string(),
  lane: __t.u8(),
  pos: __t.f64(),
  seq: __t.u32(),
  item: __t.string(),
});
export type RaceFeature = __Infer<typeof RaceFeature>;

export const RaceItem = __t.object('RaceItem', {
  identity: __t.identity(),
  room: __t.string(),
  held: __t.string(),
  slowTicks: __t.u32(),
  shieldTicks: __t.u32(),
  turboTicks: __t.u32(),
});
export type RaceItem = __Infer<typeof RaceItem>;

export const RacePlayer = __t.object('RacePlayer', {
  identity: __t.identity(),
  room: __t.string(),
  name: __t.string(),
  duckIndex: __t.u8(),
  active: __t.bool(),
  lane: __t.f64(),
  steer: __t.f64(),
  pos: __t.f64(),
  vel: __t.f64(),
  taps: __t.u32(),
  boostMeter: __t.u32(),
  boostTicksLeft: __t.u32(),
  place: __t.u32(),
  rank: __t.u32(),
  lastTapAt: __t.u64(),
  drowned: __t.bool(),
  bonks: __t.u32(),
  seconds: __t.f64(),
});
export type RacePlayer = __Infer<typeof RacePlayer>;

export const RaceResult = __t.object('RaceResult', {
  id: __t.string(),
  room: __t.string(),
  raceNumber: __t.u32(),
  identity: __t.identity(),
  name: __t.string(),
  duckIndex: __t.u8(),
  place: __t.u32(),
  taps: __t.u32(),
  pos: __t.f64(),
  drowned: __t.bool(),
  bonks: __t.u32(),
  seconds: __t.f64(),
});
export type RaceResult = __Infer<typeof RaceResult>;

export const RaceTick = __t.object('RaceTick', {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type RaceTick = __Infer<typeof RaceTick>;

export const Stats = __t.object('Stats', {
  id: __t.u8(),
  visitors: __t.u32(),
  players: __t.u32(),
  races: __t.u32(),
  soloRuns: __t.u32(),
});
export type Stats = __Infer<typeof Stats>;

export const Visitor = __t.object('Visitor', {
  identity: __t.identity(),
  firstSeen: __t.timestamp(),
  lastSeen: __t.timestamp(),
  visits: __t.u32(),
});
export type Visitor = __Infer<typeof Visitor>;
