import {useRef,useMemo} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {Html} from '@react-three/drei';
import * as THREE from 'three';
import Duck3D from './Duck3D';
import SceneBoundary from './SceneBoundary';
import {PAL,laneX} from '../palette';
import type {RacePlayer,Race} from '../module_bindings/types';
function Racer({p,mine}:{p:RacePlayer;mine:boolean}){const ref=useRef<THREE.Group>(null);const initial=useMemo<[number,number,number]>(()=>[laneX(p.identity.toHexString()),0,-p.pos/10],[]);useFrame((_,dt)=>{if(!ref.current)return;const z=-p.pos/10;if(Math.abs(ref.current.position.z-z)>35)ref.current.position.z=z;else ref.current.position.z=THREE.MathUtils.damp(ref.current.position.z,z,12,dt)});return <group ref={ref} position={initial}><group scale={1.3}><Duck3D duckIndex={p.duckIndex} speed={p.vel} taps={p.taps}/></group><mesh rotation={[-Math.PI/2,0,0]} position={[0,.015,.2]} scale={[1.1,1.3+p.vel/75,1]}><circleGeometry args={[1,32]}/><meshBasicMaterial color={PAL.paper} transparent opacity={.22}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,.025,0]} scale={[1.1,1.4,1]}><circleGeometry args={[1,32]}/><meshBasicMaterial color={PAL.navy} transparent opacity={.14}/></mesh>{p.boostTicksLeft>0&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.05,0]}><ringGeometry args={[1.6,1.85,48]}/><meshBasicMaterial color={PAL.pink}/></mesh>}<Html position={[0,3.5,0]} center distanceFactor={18} zIndexRange={[1,0]}><div className={`name-tag ${mine?'you':''}`}>{mine?'YOU':p.name}</div></Html></group>}
function Camera({target,spectator}:{target?:RacePlayer;spectator:boolean}){const initialized=useRef(false);useFrame(({camera},dt)=>{const z=-(target?.pos??0)/10,x=target?laneX(target.identity.toHexString()):0;const destination=new THREE.Vector3(spectator?0:x,spectator?18:7,spectator?z+22:z+12);if(!initialized.current||Math.abs(camera.position.z-destination.z)>40){camera.position.copy(destination);initialized.current=true}else camera.position.lerp(destination,1-Math.exp(-5*dt));camera.lookAt(spectator?x:x*.8,1,z-15);const cam=camera as THREE.PerspectiveCamera;cam.fov=THREE.MathUtils.damp(cam.fov,62+(target?.vel??0)*.025,3,dt);cam.updateProjectionMatrix()});return null}
function Streaks({target}:{target?:RacePlayer}){const ref=useRef<THREE.InstancedMesh>(null);const dummy=useMemo(()=>new THREE.Object3D(),[]);useFrame(({clock})=>{if(!ref.current)return;const speed=target?.vel??0,z=-(target?.pos??0)/10;for(let i=0;i<48;i++){dummy.position.set(((i*7.37)%29)-14.5,.04,z-55+((i*8.1+clock.elapsedTime*(2+speed*.15))%70));dummy.scale.set(speed>20?.055+speed*.0004:.035,1,.4+speed*.015);dummy.updateMatrix();ref.current.setMatrixAt(i,dummy.matrix)}ref.current.instanceMatrix.needsUpdate=true});return <instancedMesh ref={ref} args={[undefined,undefined,48]}><boxGeometry args={[1,.02,1]}/><meshBasicMaterial color={target?.boostTicksLeft?PAL.pink:'#a7d2ff'} transparent opacity={.55}/></instancedMesh>}
function Track({race}:{race:Race}){return <><color attach="background" args={[PAL.sand]}/><fog attach="fog" args={[PAL.sand,55,145]}/><hemisphereLight args={['#fffdf6','#b69d6b',2]}/><directionalLight position={[-10,24,15]} intensity={2.6} color="#fff2da"/><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.06,-120]}><planeGeometry args={[32,330]}/><meshStandardMaterial color={PAL.water} roughness={.3} metalness={.12}/></mesh>{[-1,1].map(side=><group key={side}><mesh position={[side*25,-.4,-120]}><boxGeometry args={[18,1,340]}/><meshStandardMaterial color={PAL.sand}/></mesh>{Array.from({length:26},(_,i)=><group key={i} position={[side*15.1,.25,12-i*10]}><mesh><coneGeometry args={[.33,.85,16]}/><meshStandardMaterial color={i%2?PAL.paper:PAL.pink}/></mesh><mesh position={[0,-.16,0]}><cylinderGeometry args={[.46,.46,.14,20]}/><meshStandardMaterial color={PAL.paper}/></mesh></group>)}</group>)}<group position={[0,0,-8]}>{[-1,1].map(s=><mesh key={s} position={[s*15,4,0]}><boxGeometry args={[.5,8,.5]}/><meshStandardMaterial color={PAL.navy}/></mesh>)}<mesh position={[0,7.7,0]}><boxGeometry args={[30,1.5,.6]}/><meshStandardMaterial color={PAL.paper}/></mesh>{[0,1,2].map(i=><mesh key={i} position={[(i-1)*1.5,7.7,.4]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.48,.48,.15,24]}/><meshStandardMaterial color={race.status==='racing'?PAL.water:race.status==='countdown'&&Math.ceil(race.phaseTicksLeft/10)<=3-i?(i===2?PAL.yellow:PAL.pink):PAL.navy}/></mesh>)}</group><group position={[0,0,-240]}>{[-1,1].map(s=><mesh key={s} position={[s*15,4,0]}><boxGeometry args={[.6,8,.6]}/><meshStandardMaterial color={PAL.navy}/></mesh>)}<mesh position={[0,7.5,0]}><boxGeometry args={[30,2,.6]}/><meshStandardMaterial color={PAL.pink}/></mesh><Html position={[0,7.5,.4]} center distanceFactor={35} zIndexRange={[1,0]}><div style={{fontWeight:700,fontSize:28,letterSpacing:5}}>FINISH</div></Html>{Array.from({length:32},(_,i)=><mesh key={i} rotation={[-Math.PI/2,0,0]} position={[-15+(i%16)*2,.02,Math.floor(i/16)*2]}><planeGeometry args={[2,2]}/><meshBasicMaterial color={(i+Math.floor(i/16))%2?PAL.paper:PAL.navy}/></mesh>)}</group></>}
export default function RaceScene({race,players,identity}:{race:Race;players:readonly RacePlayer[];identity:string}){const mine=players.find(p=>p.identity.toHexString()===identity);const target=mine?.active?mine:players.find(p=>p.active&&p.rank===1);return <SceneBoundary><Canvas camera={{position:[0,8,15],fov:62}} dpr={[1,1.6]} gl={{antialias:true,alpha:true}}><Track race={race}/><Camera target={target} spectator={!mine?.active}/><Streaks target={target}/>{players.filter(p=>p.active).map(p=><Racer key={p.identity.toHexString()} p={p} mine={p.identity.toHexString()===identity}/>)}</Canvas></SceneBoundary>}
